services:
  gateway_1:
    image: gateway
    build:
      context: .
      dockerfile: Gateway/Dockerfile
    environment:
      - GATEWAY_ID=1
    volumes:
      - ./Gateway/config_gateway_1.json:/app/config_gateway_1.json

  gateway_2:
    image: gateway
    build:
      context: .
      dockerfile: Gateway/Dockerfile
    environment:
      - GATEWAY_ID=2
    volumes:
      - ./Gateway/config_gateway_2.json:/app/config_gateway_2.json
  
  gateway_3:
    image: gateway
    build:
      context: .
      dockerfile: Gateway/Dockerfile
    environment:
      - GATEWAY_ID=3
    volumes:
      - ./Gateway/config_gateway_3.json:/app/config_gateway_3.json
  
  server:
    image: server
    build:
      context: .
      dockerfile: Server/Dockerfile
    volumes:
      - ./Server/ConfigurationManagement:/app/ConfigurationManagement
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=true

  nats:
    image: nats:latest
    ports:
      - "4222:4222"
      - "8222:8222"
    environment:
      - NATS_SERVER_NAME=nats

