services:
  gateway_1:
    image: gateway
    build:
      context: .
      dockerfile: Gateway/Dockerfile
    environment:
      - GATEWAY_ID=00:1A:2B:3C:4D:5E
      - CONFIG_FILE=/app/gateway_1_config.json
    volumes:
      - ./Gateway/gateway_1_config.json:/app/gateway_1_config.json

  gateway_2:
    image: gateway
    build:
      context: .
      dockerfile: Gateway/Dockerfile
    environment:
      - GATEWAY_ID=00:1B:44:11:3A:B7
      - CONFIG_FILE=/app/gateway_2_config.json
    volumes:
      - ./Gateway/gateway_2_config.json:/app/gateway_2_config.json
  
  gateway_3:
    image: gateway
    build:
      context: .
      dockerfile: Gateway/Dockerfile
    environment:
      - GATEWAY_ID=00:1D:92:7E:5F:2C
      - CONFIG_FILE=/app/gateway_3_config.json
    volumes:
      - ./Gateway/gateway_3_config.json:/app/gateway_3_config.json
      
  server:
    image: server
    build:
      context: .
      dockerfile: Server/Dockerfile
    volumes:
      - ./Server/ConfigurationManagement:/app/ConfigurationManagement
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=true

  nats:
    image: nats:latest
    ports:
      - "4222:4222"
      - "8222:8222"
    environment:
      - NATS_SERVER_NAME=nats

